### ISSUE TITLE
When unit is set to %, diagram breaks. 

### ISSUE THREAD

**Issue by Novop** [dumptyd/vue-css-donut-chart#10]
Using In-browser resource
<link href="https://unpkg.com/vue-css-donut-chart/dist/vcdonut.css">
<script src="https://unpkg.com/vue-css-donut-chart"></script>

When unit is set to %, diagram breaks. 

Had to revert to 1.0.2 version.

**Comment by dumptyd** [comment]
Thanks @pashis, I completely overlooked that.
It has been fixed now in 1.1.3. :slightly_smiling_face:
