### ISSUE TITLE
No tests?

### ISSUE THREAD

**Issue by ThePeach** [dumptyd/vue-css-donut-chart#11]
I've stumbled upon this component but I was wondering if there was any intention to add any test coverage to the code base

**Comment by dumptyd** [comment]
I've been meaning to add tests for some time. It's a work in progress right now, you can track it in [this branch](https://github.com/dumptyd/vue-css-donut-chart/tree/add-tests).

**Comment by dumptyd** [comment]
This has been done. ![Codecov](https://img.shields.io/codecov/c/gh/dumptyd/vue-css-donut-chart)
