### ISSUE TITLE
HTML in text field

### ISSUE THREAD

**Issue by dhruvturakhia** [dumptyd/vue-css-donut-chart#13]
Wouldn't it be better practice to have a field asking for enabling HTML and then enabling the use of v-html. than comparing the input format to be HTML and run a v-html to DonutHTML?

**Comment by dhruvturakhia** [comment]
> Wouldn't it be better practice to have a field asking for enabling HTML and then enabling the use of v-html. than comparing the input format to be HTML and run a v-html to DonutHTML?

Yeah, I figured on how you enter the HTML and it was completely a developers decision.

**Comment by dumptyd** [comment]
Were you talking about the textarea on the demo site?

And no problem. Let me know if you have any other questions about the library. 🙂
