### ISSUE TITLE
[Feature request] Section hover event/callback

### ISSUE THREAD

**Issue by salunet** [dumptyd/vue-css-donut-chart#19]
I would like to be able to handle hover on sections, just click the click event.

**Comment by dumptyd** [comment]
@salunet Would you mind telling what your use case is? What would you want to do on section hover?

**Comment by salunet** [comment]
So i can show some element with text (description) in it.

**Comment by dgattey** [comment]
yeah I too would love to show a tooltip on hover with the label and value!

**Comment by dumptyd** [comment]
Sorry for the delay, guys. It's out now under 1.2.0.

---

**Changelog:** https://github.com/dumptyd/vue-css-donut-chart/blob/master/CHANGELOG.md
**Demo:** https://dumptyd.github.io/vue-css-donut-chart/
**Documentation:** https://github.com/dumptyd/vue-css-donut-chart#events
