### ISSUE TITLE
Sum of all the sections' values (100.00000000000001) should not exceed `total` (100)"

### ISSUE THREAD

**Issue by toms427** [dumptyd/vue-css-donut-chart#24]
I recently stumbled upon this error. If I pass exactly this array to the chart receive this error
doesntWork =[{color: 'red', value:8.2}, {color: 'green', value:34.97}, {color: 'blue', value:30.6}, {color: 'yellow', value:26.23}]
But if I switch order of the array it works.
works = [{color: 'green', value:34.97}, {color: 'red', value:26.23}, {color: 'yellow', value:8.2}, {color: 'blue', value:30.6},  ]

**Comment by dumptyd** [comment]
@toms427 This has been fixed in version 1.2.0. Thanks for reporting this issue.

---

**Changelog:** https://github.com/dumptyd/vue-css-donut-chart/blob/master/CHANGELOG.md
**Demo:** https://dumptyd.github.io/vue-css-donut-chart/
