### ISSUE TITLE
How hide this line?

### ISSUE THREAD

**Issue by Feduch** [dumptyd/vue-css-donut-chart#41]
Hi!

Very fine donut chart!

How hide this line?

![DeepinScreenshot_выберите-область_20201125151209](https://user-images.githubusercontent.com/5888590/100226320-a0582900-2f30-11eb-8a26-94b7be9c4a86.png)

**Comment by dumptyd** [comment]
@Feduch Seems like the same issue as this: https://github.com/dumptyd/vue-css-donut-chart/issues/32. @An-angrybear has posted a workaround in that issue. I'll try to look into it more over the weekend.
