### ISSUE TITLE
Vue 3 usage

### ISSUE THREAD

**Issue by dhanielcodes** [dumptyd/vue-css-donut-chart#44]
I tried using your package with vue 3, but it doesn't work properly
How do I set it up for vue 3

This is my code buh didn't work

```javascipt
import { createApp } from 'vue'
import App from './App.vue'
import Donut from 'vue-css-donut-chart';
import 'vue-css-donut-chart/dist/vcdonut.css';

const app = createApp(App)
app.use(Donut)
app.mount('#app')
```

**Comment by narekkay** [comment]
Did you find any solution?

**Comment by dhanielcodes** [comment]
Nope, I had to switch to Apex charts, they had for vue 3

**Comment by narekkay** [comment]
Yes! I can confirm, Apex Charts works on Vue 3 👍

**Comment by dhanielcodes** [comment]
👍

**Comment by pixelpep** [comment]
Still not in vue3?

**Comment by narekkay** [comment]
Didn't test Idk😬 Haven't seen any update on their git / npm repo so **it's most likely that it still doesn't work...**

**Comment by dumptyd** [comment]
_Soon_ ™

On a serious note, I am running into some issues with porting the tests, but I will try to get a version out for Vue 3 within next couple of weeks.

**Comment by dumptyd** [comment]
This should be working now. 

- Docs: https://github.com/dumptyd/vue-css-donut-chart/tree/next
- Demo: https://dumptyd.github.io/vue-css-donut-chart/next/
- NPM: https://www.npmjs.com/package/vue-css-donut-chart/v/next
