### ISSUE TITLE
Animation

### ISSUE THREAD

**Issue by Jwdev-wr** [dumptyd/vue-css-donut-chart#6]
Hey excellent css donut chart!

I think the only thing it is missing is an animation for when the chart loads. Most donut charting libraries will bring the donut chart in slowly around the radius of the chart.

Anyway you could implement this quickly? I'm strapped for time but if you are also strapped for time I can submit a PR. 

Best regards.

**Comment by dumptyd** [comment]
Thanks @WhiteRaBot17, and I agree that animation is something that goes hand-in-hand with chart libs. However, I don't think making animation work with this lib is a task that can be done quickly.

So, I don't see it being implemented in the lib anytime in the near future, sorry. :disappointed:

**Comment by Santosh-TECHO** [comment]
When this can be done? 🤒
