### ISSUE TITLE
Cannot read properties of undefined (reading '_c')

### ISSUE THREAD

**Issue by leo-carey** [dumptyd/vue-css-donut-chart#65]
I've ran but show this error:
Cannot read properties of undefined (reading '_c')

My code:

```
import Donut from 'vue-css-donut-chart';

const app = createApp();
app.use(Donut);

...

<template>
  <vc-donut total="35">
    Test donut
  </vc-donut>
</template>
```

**Comment by dumptyd** [comment]
What version of the library do you have installed? Vue 3 requires ^2.0.0 to work. 

Make sure you follow the installation instructions from here - https://github.com/dumptyd/vue-css-donut-chart/tree/next

**Comment by leo-carey** [comment]
@dumptyd yes, my vue version in package.json:
"vue": "^3.2.13"

**Comment by leo-carey** [comment]
@dumptyd I'm using 2.0.0 now and works now!
