### ISSUE TITLE
can we use this library by directly importing in the component

### ISSUE THREAD

**Issue by roshan2921** [dumptyd/vue-css-donut-chart#67]
I want to use this package after installing by directly importing into my component

**Comment by roshan2921** [comment]
@dumptyd @frados @christikaes

**Comment by dumptyd** [comment]
@roshan2921 Yes you can. This should help you https://github.com/dumptyd/vue-css-donut-chart/issues/18#issuecomment-549539239.

```js
import Donut from 'vue-css-donut-chart/src/components/Donut.vue';
```
