### ISSUE TITLE
[Feature request] Section click event/callback 

### ISSUE THREAD

**Issue by greabock** [dumptyd/vue-css-donut-chart#7]
I would like to be able to handle clicks on sections.

**Comment by dumptyd** [comment]
I think this would be useful. I'll include this in the next minor release.

**Comment by dumptyd** [comment]
Feature published. :tada: Upgrade your package version to 1.1.2

https://github.com/dumptyd/vue-css-donut-chart/blob/master/CHANGELOG.md#112
