### ISSUE TITLE
[Feature request] Starting angle

### ISSUE THREAD

**Issue by greabock** [dumptyd/vue-css-donut-chart#8]
I would like to be able to specify the starting angle from which the first section begins.

**Comment by dumptyd** [comment]
This could be useful too. I'll include this in the next minor release too.

**Comment by dumptyd** [comment]
Feature published. :tada: Upgrade your package version to 1.1.2

https://github.com/dumptyd/vue-css-donut-chart/blob/master/CHANGELOG.md#112
